podAnnotations: {}

service:
  type: NodePort
  ports:
  - name: status-port
    port: 15021
    targetPort: 15021
  - name: http2
    port: 80
    targetPort: 8080
    nodePort: 32080
  - name: https
    port: 443
    targetPort: 8443
    nodePort: 32443
  - name: tls
    port: 15443
    targetPort: 15443

autoscaling:
  enabled: false
