apiVersion: kit/v1
kind: Tasks
metadata:
  name: install-kind-and-istio
  annotations:
    help: |
      Install `kit` by following https://github.com/kitproj/kit#install.

      Run `kit up` to start.
spec:
  tasks:
    - name: install-kind-cluster
      command: kind create cluster --config config.yaml
      watch: kind_cluster/config.yaml
      workingDir: kind_cluster
    - name: install-istioctl
      command:
      - sh
      - -c
      - |
        # download istio latest version
        curl -L https://istio.io/downloadIstio | sh -
      dependencies: install-kind-cluster
    - name: up
      dependencies: install-istioctl
